version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production