# Override file for development
# This file is automatically merged with docker-compose.yml
version: '3.8'

services:
  backend:
    # Enable hot reloading for development
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=true
    # Override command for development with auto-reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  postgres:
    # Expose PostgreSQL port for external connections during development
    ports:
      - "5432:5432"
    # Enable logging for debugging
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]